ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls")),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('cart', views.view_cart, name="cart"),
    path('add/<int:id>/', views.add_cart, name='add_cart'),
    path('remove/<int:id>/', views.remove_cart, name='remove_cart'),
    path('register', views.register, name="register"),
    path('order', views.order, name="order"),
    path('check/<int:id>/', views.detail, name='detail'),
    path('update_cart/<int:item_id>/', views.update_cart, name='update_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('apply_promo_code/', views.apply_promo_code, name='apply_promo_code'),
    path('update_shipping_cost/', views.update_shipping_cost, name='update_shipping_cost'),
    path('ordered/', views.ordered, name='ordered')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from phonenumber_field.modelfields import PhoneNumberField
from creditcards.models import CardNumberField, CardExpiryField, SecurityCodeField
from localflavor.br.models import BRPostalCodeField, BRStateField

# Create your models here.


class Item(models.Model):

    CATEGORY_CHOICES = (
        ('bracelets', 'Bracelets'),
        ('dresses', 'Dresses'),
        ('earrings', 'Earrrings'),
        ('necklaces', 'Necklaces'),
        ('tshirts', 'Tshirts'),
        ('watches', 'Watches'),
        ('pants', 'Pants'),
        ('skirts', 'Skirts'),
        ('bags', 'Bags')
    )

    SIZE_CHOICES = (
        ('small', 'Small'),
        ('medium', 'Medium'),
        ('large', 'Large'),
        ('extra_large', 'Extra Large'),
    )

    name = models.CharField(max_length=15)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    size = models.CharField(max_length=15, choices=SIZE_CHOICES, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CartBase(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    items = models.ManyToManyField(Item, through='CartItem')

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):  # intermedio entre Cart e Item
    cart = models.ForeignKey(CartBase, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.item.name}"

    def total_price(self):
        return self.quantity * self.item.price

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(
        max_length=100, null=True)  # Permitindo valor nulo
    last_name = models.CharField(
        max_length=100, null=True)  # Permitindo valor nulo
    number = PhoneNumberField(null=True)

    # Email
    email = models.CharField(max_length=100, null=True)

    # Address
    number_house = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    street = models.CharField(max_length=255, null=True)
    state = BRStateField('Estado', null=True)
    postal_code = BRPostalCodeField('CEP', null=True)

    # Payment
    card_name = models.CharField(
        max_length=16, null=True)
    card_number = CardNumberField('Número do Cartão', null=True)
    card_expiration = CardExpiryField('Data de Validade', null=True)
    card_cvv = SecurityCodeField('CVV/CVC', null=True)

    def __str__(self):
        return f"Profile From: {self.user}"

class PromoCode(models.Model):
    # Código do cupom promocional
    code = models.CharField(max_length=20, unique=True)
    # Valor de desconto (porcentagem)
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    expiration_date = models.DateField()  # Data de validade do cupom
    # Relacionamento muitos para muitos com usuários que já usaram o cupom
    users_used = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.code

    def can_be_used_by_user(self, user):
        """
        Verifica se o usuário pode usar o cupom.
        Retorna True se o cupom não expirou e ainda não foi usado pelo usuário.
        """
        return not self.users_used.filter(id=user.id).exists() and self.expiration_date >= timezone.now().date()

    def mark_as_used_by_user(self, user):
        """
        Marca o cupom como usado pelo usuário.
        """
        self.users_used.add(user)
        self.save()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Referência ao carrinho do usuário
    cart = models.ForeignKey(CartBase, on_delete=models.SET_NULL, null=True)
    user_profile = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True)
    order_date = models.DateTimeField(auto_now_add=True)
    total_amount = models.DecimalField(
        max_digits=10, decimal_places=2, default=0)
    # Pode ser 'Pending', 'Shipped', 'Delivered', etc.
    status = models.CharField(max_length=20, default='Pending')
        # Adicione a relação ManyToMany para os itens do pedido
    items = models.ManyToManyField(Item, through='OrderItem')

        # Reference to PromoCode
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)
    
    # Shipping information
    shipping_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    def __str__(self):
        return f"Order for {self.user.username} ({self.order_date})"

    def calculate_total_amount(self):
        self.total_amount = 0
        cart_items = self.cart.cartitem_set.all()

        for cart_item in cart_items:
            self.total_amount += cart_item.total_price()

        if self.promo_code:
            self.total_amount -= self.promo_code.discount
        self.save()

        return self.total_amount
    
   
    def calculate_total_itens(self):
        total_itens = 0
        order_items = OrderItem.objects.filter(order=self)  # Filtra os OrderItems relacionados a este pedido

        for order_item in order_items:
            total_itens += order_item.total_price_order()

        return total_itens

    def apply_promo_code(self, promo_code):
        try:
            promo = PromoCode.objects.get(code=promo_code)
            self.promo_code = promo
            # Aplique o desconto ao total_amount
            self.total_amount -= promo.discount
            self.save()
            return True

        except PromoCode.DoesNotExist:
            return False

    def apply_shipping(self, shipping_cost):
        self.shipping_cost = shipping_cost
        #self.calculate_total_amount()
        #self.total_amount += shipping_cost
        self.total_amount = self.calculate_total_amount() + shipping_cost
        self.save()
        return True

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return f"Order: {self.order.user.username} - From: {self.order.order_date}"

    def total_price_order(self):
        return self.quantity * self.item.price

store/views.py
from decimal import Decimal
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.views.decorators.cache import cache_control

from .forms import LoginForm, RegisterForm, ProfileForm
from .models import Item, CartBase, CartItem, Profile, Order, OrderItem, PromoCode


def index(request):
    user_cart = None
    if request.user.is_authenticated:
        user_cart, created = CartBase.objects.get_or_create(user=request.user)
    context = {"products": Item.objects.all(), "user_cart": user_cart}
    return render(request, "store/index.html", context)


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            context = {"form": form}
            return render(request, "store/register.html", context)
    return render(request, "store/register.html", {"form": RegisterForm()})


def add_cart(request, id):
    if request.method == "POST":  # Ajax
        item = get_object_or_404(Item, pk=id)

        if request.user.is_authenticated:
            user = request.user
            cart, created = CartBase.objects.get_or_create(user=user)
            cart_item, item_created = CartItem.objects.get_or_create(cart=cart, item=item)

            if not item_created:
                cart_item.quantity += 1
                cart_item.save()

            return JsonResponse({"cart_quantity": cart.items.count()})
        else:
            return redirect("login")
    else:
        item = get_object_or_404(Item, pk=id)

        if request.user.is_authenticated:
            user = request.user
            cart, created = CartBase.objects.get_or_create(user=user)
            cart_item, item_created = CartItem.objects.get_or_create(cart=cart, item=item)

            if not item_created:
                cart_item.quantity += 1
                cart_item.save()

            return redirect("cart")
        else:
            return redirect("login")


def remove_cart(request, id):
    cart_item = get_object_or_404(CartItem, pk=id)

    if request.user.is_authenticated and cart_item.cart.user == request.user:
        cart_item.delete()

    return redirect("cart")


def view_cart(request):
    if request.user.is_authenticated:
        user = request.user
        cart, created = CartBase.objects.get_or_create(user=user)
        cart_items = CartItem.objects.filter(cart=cart)
    else:
        cart_items = []

    return render(request, "store/cart.html", {"cart_items": cart_items, "user_cart": cart, })


def detail(request, id):
    item = Item.objects.get(pk=id)
    related_items = Item.objects.filter(category=item.category).exclude(pk=id)[:4]
    return render(request, "store/detail.html", {"item": item, "products": related_items})


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return render(
                    request,
                    "store/login.html",
                    {"message": "Invalid Credentials", "form": LoginForm()},
                )

    elif request.method == "GET":
        return render(request, "store/login.html", {"form": LoginForm()})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


@login_required
def order(request):
    user = request.user
    context = {"orders": Order.objects.filter(status="Finished", user=user), }
    return render(request, "store/order.html", context)


def update_cart(request, item_id):
    user = request.user
    cart = CartBase.objects.get(user=user)
    if request.method == "POST":
        item = get_object_or_404(CartItem, id=item_id)
        nova_quantidade = int(request.POST.get("quantity"))
        if nova_quantidade <= 0:
            item.delete()
            has_item = cart.cartitem_set.exists()
            return JsonResponse({"message": "Item removido do carrinho", "itemdeleted": item_id,
                                 "has_item": has_item, "cart_quantity": cart.items.count(), })
        item.quantity = nova_quantidade
        item.save()
        item_total_price = item.total_price()
        return JsonResponse(
            {
                "message": "Quantidade atualizada com sucesso",
                "item_total_price": item_total_price,
                "cart_quantity": cart.items.count()
            }
        )


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def ordered(request):
    return render(request, "store/ordered.html")


@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def checkout(request):
    user = request.user
    if request.user.is_authenticated:
        user_cart, created = CartBase.objects.get_or_create(user=request.user)

    if request.method == "POST":
        orders = Order.objects.filter(user=user)

        if orders.exists():
            order = orders.latest('order_date')
            profile_form = ProfileForm(
                request.POST,
                instance=user.profile if hasattr(user, "profile") else None,
            )

            if profile_form.is_valid():
                profile = profile_form.save(commit=False)
                profile.user = user
                profile.save()

                order.status = "Finished"
                order.user_profile = profile
                order.save()

                for cart_item in order.cart.cartitem_set.all():
                    OrderItem.objects.create(order=order, item=cart_item.item, quantity=cart_item.quantity)

                order.cart.delete()
                return redirect("ordered")
            else:
                return render(request, "store/checkout.html", {
                    "profile_form": profile_form,
                    "order": order,
                    "cart_items": order.cart.cartitem_set.all(),
                    "total_amount": order.calculate_total_amount(),
                    "user_cart": user_cart,
                })

    orders = Order.objects.filter(user=user)

    if orders.exists():
        order = orders.latest('order_date')
    else:
        order = Order.objects.create(user=user)
        order.cart = CartBase.objects.get(user=user)
        order.save()

    if order.status == "Finished":
        new_order = Order.objects.create(user=user)
        new_order.save()
        new_order.cart = CartBase.objects.get(user=user)
        new_order.save()
        order = new_order

    cart_items = order.cart.cartitem_set.all()
    total_amount = order.calculate_total_amount()

    try:
        profile = Profile.objects.get(user=user)
        profile_form = ProfileForm(instance=profile)
    except Profile.DoesNotExist:
        profile_form = ProfileForm()

    context = {
        "profile_form": profile_form,
        "order": order,
        "cart_items": cart_items,
        "total_amount": total_amount,
    }

    return render(request, "store/checkout.html", context)

def apply_promo_code(request):
    if request.method == "POST":
        user = request.user
        order = Order.objects.get(user=user, status="Pending")
        promo_code = request.POST.get("promo_code")

        try:
            promo = PromoCode.objects.get(code=promo_code)

            if promo.can_be_used_by_user(user):
                order.apply_promo_code(promo)
                promo.mark_as_used_by_user(user)
                return JsonResponse(
                    {
                        "message": "Código promocional aplicado com sucesso.",
                        "discount": promo.discount,
                        "updated_price": order.total_amount,
                    }
                )
            else:
                return JsonResponse(
                    {
                        "message": "Cupom inválido ou expirado",
                        "discount": 0,
                        "updated_price": order.total_amount,
                    }
                )

        except PromoCode.DoesNotExist:
            return JsonResponse({"message": "Código promocional inválido."}, status=400)

def update_shipping_cost(request):
    if request.method == "POST":
        user = request.user
        order = Order.objects.get(user=user, status="Pending")
        shipping_option = request.POST.get("shipping_option")

        if shipping_option == "express":
            shipping_cost = Decimal(14.00)
        elif shipping_option == "post_office":
            shipping_cost = Decimal(10.00)
        elif shipping_option == "self_pickup":
            shipping_cost = Decimal(0.00)
        else:
            shipping_cost = 0.00

        order.apply_shipping(shipping_cost)

        return JsonResponse(
            {
                "message": "Custo de envio atualizado com sucesso.",
                "taxe": order.total_amount,
            }
        )

store/templates/store/cart.html
{% extends "store/layout.html" %} {% block content %} {% load static %} {% csrf_token %}

<section class="h-100">
  <div class="container h-100 py-5">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-10">
        <div class="d-flex justify-content-between align-items-center mb-4">
          <h3 class="fw-normal mb-0 text-black">Carrinho de compras</h3>
        </div>
        {% if cart_items %}
        <!-- Loop para exibir itens no carrinho -->
        {% for cart_item in cart_items %}
        <div class="card rounded-3 mb-4" id="cart{{cart_item.id}}">
          <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-md-2 col-lg-2 col-xl-2">
                <!-- Imagem do item -->
                <img
                  src="{{ cart_item.item.image.url }}"
                  class="img-fluid rounded-3"
                  alt="{{ cart_item.item.name }}"
                />
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <!-- Nome e informações do item -->
                <p class="lead fw-normal mb-2">{{ cart_item.item.name }}</p>
                {% if cart_item.item.size %}
                <p>
                  <span class="text-muted">Size: </span>{{ cart_item.item.size}}
                  P
                </p>
                {% endif %} {% if cart_item.item.size %}
                <p>
                  <span class="text-muted"> Color: </span> {{
                  cart_item.item.color }} R
                </p>
                {% endif %}
              </div>

              <!-- Botões de quantidade -->
              <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                <input
                  id="form{{ cart_item.id }}"
                  min="0"
                  name="quantity"
                  value="{{ cart_item.quantity }}"
                  type="number"
                  class="form-control form-control-sm"
                  onchange="updateCart(this)"
                />
              </div>

              <!-- Preço total do item -->
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0" id="totalprice{{ cart_item.id }}">
                  R${{ cart_item.total_price }}
                </h5>
              </div>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <!-- Link para remover item do carrinho -->
                <a
                  href="{% url 'remove_cart' cart_item.id %}"
                  class="text-danger"
                >
                  <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %} {% else %}
        <h4>No itens.</h4>
        {% endif %}
        <h4 id="Empty"></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-11">
        <div class="float-end mt-4">
          <a href="{% url 'index'%}" style="text-decoration: none">
            <button class="btn btn-light border">Voltar</button>
          </a>

          {% if cart_items|length >= 1 %}
          <a href="{% url 'checkout'%}" style="text-decoration: none">
            <button class="btn btn-success shadow-0 border" id="check">
              Checkout
            </button>
          </a>
          {% else %}
          <!-- Desativar o botão de checkout se houver menos de dois produtos no carrinho -->
          <button class="btn btn-success shadow-0 border" disabled>
            Checkout
          </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

<script>
function updateCart(inputElement) {
   var cartItemId = inputElement.id.replace("form", ""); // Obtém o ID do item no carrinho
   var quantity = inputElement.value; // Obtém o novo valor do campo de entrada
   var csrfToken = $("[name='csrfmiddlewaretoken']").val();

   $.ajax({
      type: "POST",
      url: "/update_cart/" + cartItemId + "/", 
      data: { quantity: quantity, csrfmiddlewaretoken: csrfToken},
      success: function (response) {
         var updatedItemTotal = response.item_total_price;
         var deleteditem = response.itemdeleted;
         var hasitem = response.has_item;
         var cartQuantity = response.cart_quantity;
         var itemPriceElement = document.getElementById("totalprice" + cartItemId); 
         
         if (hasitem == false) {
             document.getElementById("check").disabled = true;
             console.log(hasitem);
             document.getElementById("Empty").textContent = "Sem itens."
         } 

         if (deleteditem) {
            //remover por id
            console.log('cart' + deleteditem)
            document.getElementById("cart" + deleteditem).remove()
         }
         else if (updatedItemTotal) {
            itemPriceElement.textContent = "R$" + updatedItemTotal;
         }
         document.getElementById("cart-quantity").textContent = cartQuantity;
      },
      error: function () {
         alert("Ocorreu um erro ao atualizar o carrinho.");
      },
   });
}
</script>
{% endblock %}

store/templates/store/detail.html
{% extends "store/layout.html" %} {% block content %}
<!-- templates/store/detail.html -->

<!-- CARROUSEL -->
<div class="container mt-4 mb-5">
  <div class="row">
    <div class="col-md-6">
      <div id="productCarousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <!-- Primeiro slide do carrossel (marcado como ativo) -->
            <img
              src="{{ item.image.url }}"
              class="d-block w-100 carousel-image"
              alt="{{ item.name }}"
            />
            <!-- Imagem do primeiro produto no slide do carrossel -->
          </div>
        </div>
        <a
          class="carousel-control-prev"
          href="#productCarousel"
          role="button"
          data-slide="prev"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a
          class="carousel-control-next"
          href="#productCarousel"
          role="button"
          data-slide="next"
        >
          <span class="carousel-control-next-icon" ariahidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <!-- RELATED PRODUCTS-->
    <div class="col-md-6">
      <h1>{{ item.name }}</h1>
      <p class="text-muted lead">R${{ item.price }}</p>
      <p class="text-sm mb-4"> {{item.description}}
      </p>
      <div class="col-md-3 pl-sm-0">
        <a
          class="btn btn-dark btn-md btn-block h-100 d-flex align-items-center justify-content-center px-0"
          href="{% url 'add_cart' item.id %}"
          >Adicionar ao carrinho</a
        >
      </div>
    </div>
  </div>
</div>

<!-- RELATED PRODUCTS-->
<div class="container">
  <h2 class="h5 text-uppercase mb-4">Related products</h2>
  <div class="row mb-4">
    {% if products %}
    {% for product in products %}
    <div class="col-md-3 col-sm-6">
      <div class="product-grid">
        <div class="product-image">
          <!-- Imagem exibição -->
          <a href="{% url 'detail' product.id %}">
            <img
              class="pic-1"
              src="{{ product.image.url }}"
              alt="{{ product.name }}"
            />
            <img
              class="pic-2"
              src="{{ product.image.url }}"
              alt="{{ product.name }}"
            />
          </a>
          <!-- Apendice -->
          <ul class="social">
            <li>
              <a href="{% url 'detail' product.id %}" data-tip="Quick View">
                <i class="fa fa-eye"></i>
              </a>
            </li>
            <li>
              <a href="{% url 'add_cart' product.id %}" data-tip="Add to Cart">
                <i class="fa fa-shopping-cart"></i>
              </a>
            </li>
          </ul>
        </div>
             <div class="product-content">
          <h3 class="title">
            <a href="{% url 'detail' product.id %}">{{ product.name }}</a>
          </h3>
          <span class="price"> R$ {{ product.price }}</span>
        </div>

      </div>
    </div>
    {% endfor %}
    {% else %}
    <h4> No itens.</h4>
    {% endif %}
  </div>
</div>
{% endblock %}

store/templates/store/order.html
{% extends "store/layout.html" %}
{% load static %}

{% block content %}
 <!-- Order -->
<div class="col-10 mx-auto mb-4" id="orders" style="display: block;">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h3 class="fw-normal mb-0 text-black">Pedidos Finalizados</h3>
    </div>
    {% if orders %}
        <!-- Loop para exibir pedidos finalizados -->
        {% for order in orders %}
            <div class="card rounded-3 mb-4">
                <div class="card-body p-4">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-md-3 col-lg-3 col-xl-3">
                            <!-- Número do pedido -->
                            <p class="lead fw-normal mb-2">Pedido #{{ order.pk }}</p>
                        </div>
                        <div class="col-md-3 col-lg-3 col-xl-3 text-center">
                            <!-- Data do pedido -->
                            <p class="text-muted">{{ order.order_date }}</p>
                        </div>
                        <div class="col-md-3 col-lg-3 col-xl-3 offset-lg-1 text-end">
                            <!-- Total do pedido -->
                            <h5 class="mb-0">R${{ order.total_amount }}</h5>
                        </div>
                        <div class="col-md-1 col-lg-1 col-xl-1 offset-lg-1 text-end">
                            <button type="button" class="btn btn-primary order-details-button" data-toggle="modal" data-target="#modal{{order.pk}}" data-order-id="{{order.pk}}">
                                +
                            </button>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal para detalhes do pedido -->
            <div class="modal fade" id="modal{{order.pk}}" tabindex="-1" role="dialog" aria-labelledby="modalTitle{{ order.pk }}" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="modalTitle{{ order.pk }}">Detalhes do Pedido #{{ order.pk }}</h5>
                        </div>
                        <div class="modal-body">
                            <!-- Conteúdo do modal com detalhes do pedido -->
                            <!-- Adicione outros detalhes conforme necessário -->
                            <ul>
                                <div class="row mb-1">
                                    {% for order_item in order.orderitem_set.all %}
                                    <div class="col-md-3">
                                        <img src="{{ order_item.item.image.url }}" alt="{{ order_item.item.name }}" class="img-fluid rounded">
                                    </div>
                                    <div class="col-md-9">
                                        <p class="text-muted">{{ order_item.item.name }} </p>
                                        <p>Quantidade: {{ order_item.quantity }}</p>
                                        <p>Preço unidade: {{ order_item.item.price }}</p>
                                    </div>
                                    {% endfor %}
                                </div>
                            </ul>
                           
<hr>





<div class="order-details">
    <table class="table table-borderless text-end">
        <tr>
            <th scope="row" class="text-start align-middle">Total de Itens:</th>
            <td class="text-end">${{ order.calculate_total_itens }}</td>
        </tr>

        {% if order.promo_code %}
        <tr>
            <th scope="row" class="text-start align-middle">Desconto do Cupom:</th>
            <td class="text-end align-middle">R${{ order.promo_code.discount }}</td>
        </tr>
        {% endif %}

        <tr>
            <th scope="row" class="text-start align-middle">Valor do Envio:</th>
            <td class="text-end">${{ order.shipping_cost }}</td>
        </tr>

        <tr>
            <th scope="row" class="text-start align-middle">Total do Pedido:</th>
            <td class="text-end">${{ order.total_amount }}</td>
        </tr>
    </table>
</div>
</div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" onclick="closeModal('{{ order.pk }}')">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h4>No completed orders.</h4>
    {% endif %}
</div>
</div>
</div>
</div>
</div>

<script>
    function closeModal(orderId) {
        $("#modal" + orderId).modal("hide");
    }

    document.addEventListener("DOMContentLoaded", function () {
    // Adiciona o evento de clique para os botões de detalhes de pedidos
    document.querySelectorAll(".order-details-button").forEach((button) => {
        button.addEventListener("click", function (event) {
            var orderID = this.getAttribute('data-order-id'); // Obtém o ID do pedido do atributo data-order-id
            console.log("Clicado no botão de detalhes do pedido: " + orderID);

            // Adicione aqui a lógica para exibir o modal de detalhes do pedido correspondente
            $("#modal" + orderID).modal("show");

            // Adicione mais lógica conforme necessário
        });
    });
});  
</script>
{% endblock %}